language: php

sudo: false

notifications:
  email:
    on_success: never
    on_failure: change

env:
  global:
    - RPBT_WP_TS_VERSION=trunk

matrix:
  include:
    - php: 7.2
      env: WP_VERSION=latest WP_MULTISITE=0
    - php: 7.2
      env: WP_VERSION=latest WP_MULTISITE=1
    - php: 7.2
      env: WP_VERSION=4.9 WP_MULTISITE=0 RPBT_WP_TS_VERSION=version 
    - php: 7.2
      env: WP_VERSION=4.8 WP_MULTISITE=0 RPBT_WP_TS_VERSION=version
    - php: 7.1
      env: WP_VERSION=latest WP_MULTISITE=0
    - php: 7.0
      env: WP_VERSION=latest WP_MULTISITE=0
    - php: 5.6
      env: WP_VERSION=latest WP_MULTISITE=0
    - php: 5.5
      env: WP_VERSION=latest WP_MULTISITE=0
    - php: 5.4
      env: WP_VERSION=latest WP_MULTISITE=0
    - php: 5.3
      env: WP_VERSION=latest WP_MULTISITE=0
      dist: precise

before_script:
- |
  if [[ 'trunk' != "$RPBT_WP_TS_VERSION" ]]; then
    bash bin/install-wp-tests.sh wordpress_test root '' --wp-version="$WP_VERSION" --wp-ts-version="$WP_VERSION"
  else
    bash bin/install-wp-tests.sh wordpress_test root '' --wp-version="$WP_VERSION"
  fi 
- |
  # Export Composer's global bin dir to PATH, but not on PHP 5.2:
  if [[ ${TRAVIS_PHP_VERSION:0:3} != "5.2" ]]; then
    composer config --list --global
    export PATH=`composer config --list --global | grep '\[home\]' | { read a; echo "${a#* }/vendor/bin:$PATH"; }`
  fi
- |
  # Install the specified version of PHPUnit depending on the PHP version:
  case "$TRAVIS_PHP_VERSION" in
    7.3|7.2|7.1|nightly)
      echo "Using PHPUnit 7.x"
      unit=7
      [[ 'trunk' != "$RPBT_WP_TS_VERSION" ]] && unit=6
      travis_retry composer global require "phpunit/phpunit:^$unit"
      ;;
    7.0)
      echo "Using PHPUnit 6.x"
      travis_retry composer global require "phpunit/phpunit:^6"
      ;;
    5.6|5.5|5.4|5.3)
      echo "Using PHPUnit 4.x"
      travis_retry composer global require "phpunit/phpunit:^4"
      ;;
    5.2)
      # Do nothing, use default PHPUnit 3.6.x
      echo "Using default PHPUnit, hopefully 3.6"
      ;;
    *)
      echo "No PHPUnit version handling for PHP version $TRAVIS_PHP_VERSION"
      exit 1
      ;;
  esac
script: phpunit